[versions]
activity-ktx = "1.7.2"
agp = "8.2.0-alpha08"
authsdk = "2.5.1"
kotlin = "1.8.0"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
lifecycle-livedata-ktx = "2.6.1"
material = "1.10.0-alpha05"
constraintlayout = "2.1.4"
material-icons-extended = "1.4.3"
material-icons-core = "1.4.3"
material3 = "1.2.0-alpha03"
navigation = "2.6.0"
navigation-safe-args-gradle-plugin = "2.6.0"
room = "2.5.2"
retrofit = "2.9.0"
gson = "2.10.1"
gson-converter = "2.9.0"
kotlin-serialaize-json = "1.5.0"
swiperefreshlayout = "1.2.0-alpha01"
okhttp = "4.11.0"
dagger = "2.46.1"
ui-tooling-preview = "1.4.3"
work-runtime-ktx = "2.8.1"
ktlint = "11.4.0"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-livedata-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "material-icons-core" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.0-beta02" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-tooling-preview" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-tooling-preview" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-tooling-preview" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui-tooling-preview" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
authsdk = { module = "com.yandex.android:authsdk", version.ref = "authsdk" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

#Dagger
dagger = {group = "com.google.dagger", name = "dagger" , version.ref = "dagger"}
dagger-android = {group = "com.google.dagger", name = "dagger-android", version.ref = "dagger"}
dagger-android-support = {group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger"}
dagger-compiler = {group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger"}
dagger-android-compiler = {group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger"}


navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson-converter" }


okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

kotlin-serialaize-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialaize-json" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-safe-args-gradle-plugin" }
kotlin-serialize = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
retrofit = ["retrofit2", "gson", "gson-converter"]
okhttp = ["okhttp", "okhttp-logging"]
room = ["room", "room-runtime"]
dagger = ["dagger-android-support", "dagger-android", "dagger"]
dagger-compiler = ["dagger-android-compiler", "dagger-compiler"]

